name: build
on:
  push:
    branches:
      - develop
      - feature/*
      - master
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Code repository checkout
        uses: actions/checkout@v1
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 13.5
      - name: Install Node dependencies
        run: |
          npm install
      - name: Check format of configuration files
        run: |
          npm test
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -v
      - name: Build and static test Python code
        run: |
          poetry run black --check .
          poetry run flake8 scripts
          poetry run mypy scripts
          poetry run python scripts/docs.py build
