name: publish
on:
  push:
    branches:
      - master
jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        build_arg:
          - python
          - rust
          - slim
          - typescript
    runs-on: ubuntu-latest
    steps:
      - name: Code repository checkout
        uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wolfgangwazzlestrauss/canvas
          tags: ${{ matrix.build_arg }}, 0.0.1-${{ matrix.build_arg }}
          build_args: format('{0}_build="true"', ${{ matrix.build_arg }})
