# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: publish

# Make workflow run only for commits pushed or pull requests made to the
# develop, main, and master branches.
on:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:
    branches:
      - develop
      - main
      - master

jobs:
  slim:
    name: Build and push slim Docker image tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: ./Dockerfile
          push: true
          tags: "wolfgangwazzlestrauss/canvas:slim"

  tag:
    name: Build and push {{ matrix.build_arg }} Docker image tag
    strategy:
      fail-fast: false
      matrix:
        build_arg:
          - csharp
          - go
          - lean
          - python
          - rust
          - typescript
          - vscode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build_args: ${{ matrix.build_arg }}_build="true"
          context: "."
          file: ./Dockerfile
          push: true
          tags: "wolfgangwazzlestrauss/canvas:${{ matrix.build_arg }}"

  all:
    name: Build and push latest Docker image tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build_args: csharp_build="true",go_build="true",lean_build="true",python_build="true",rust_build="true",typescript_build="true",vscode_build="true"
          context: "."
          file: ./Dockerfile
          push: true
          tags: "wolfgangwazzlestrauss/canvas:latest"

  doc:
    name: Publish repository description to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Publish description to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
          DOCKERHUB_REPOSITORY: wolfgangwazzlestrauss/canvas
          README_FILEPATH: ./README.md
