# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: release

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Get Git tag and make GitHub release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Extract tag
        id: extract_tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Bootware ${{ steps.extract_tag.outputs.tag }}
          body: >-
            See the
            [changelog](https://github.com/wolfgangwazzlestrauss/canvas/blob/${{
            steps.extract_tag.outputs.tag }}/CHANGELOG.md) for more information.

  slim:
    name: Build and push slim Docker image tag
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: ./Dockerfile
          push: true
          tags: >-
            wolfgangwazzlestrauss/canvas:${{ needs.release.outputs.tag }}-slim

  tag:
    name: Build and push {{ matrix.build_arg }} Docker image tag
    needs: release
    strategy:
      fail-fast: false
      matrix:
        build_arg:
          - csharp
          - go
          - lean
          - python
          - rust
          - typescript
          - vscode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: ${{ matrix.build_arg }}_build="true"
          context: "."
          file: ./Dockerfile
          push: true
          tags: >-
            wolfgangwazzlestrauss/canvas:${{ needs.release.outputs.tag }}-${{
            matrix.build_arg }}

  all:
    name: Build and push latest Docker image tag
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: csharp_build="true",go_build="true",lean_build="true",python_build="true",rust_build="true",typescript_build="true",vscode_build="true"
          context: "."
          file: ./Dockerfile
          push: true
          tags: "wolfgangwazzlestrauss/canvas:${{ needs.release.outputs.tag }}"

  doc:
    name: Publish repository description to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Publish description to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: wolfgangwazzlestrauss/canvas
          README_FILEPATH: ./README.md
