# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: release

on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}
    steps:
      - name: Extract tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
        id: extract_tag

  slim:
    name: Build and push slim Docker image tag
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wolfgangwazzlestrauss/canvas
          tags: ${{ needs.release.outputs.tag }}-slim

  tag:
    name: Build and push {{ matrix.build_arg }} Docker image tag
    needs: release
    strategy:
      fail-fast: false
      matrix:
        build_arg:
          - csharp
          - go
          - lean
          - python
          - rust
          - typescript
          - vscode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wolfgangwazzlestrauss/canvas
          tags: ${{ needs.release.outputs.tag }}-${{ matrix.build_arg }}
          build_args: ${{ matrix.build_arg }}_build="true"

  all:
    name: Build and push latest Docker image tag
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: wolfgangwazzlestrauss/canvas
          tags: ${{ needs.release.outputs.tag }}
          build_args: csharp_build="true",go_build="true",lean_build="true",python_build="true",rust_build="true",typescript_build="true",vscode_build="true"

  doc:
    name: Publish repository description to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Publish description to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: wolfgangwazzlestrauss/canvas
          README_FILEPATH: ./README.md
